service: user-application

frameworkVersion: "3"

package:
  patterns:
    - "!.**/**"

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  iamManagedPolicies:
    - "arn:aws:iam::XXX:policy/UserApplicationReadSecrets"

functions:
  registration:
    handler: src.integration.user_controller.registration_handler
    events:
      - http:
          path: user/register
          method: post
          integration: lambda-proxy
          cors: true

  sign_in:
    handler: src.integration.user_controller.sign_in_handler
    events:
      - http:
          path: user/sign_in
          method: post
          integration: lambda-proxy
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
